# Service catalog service.
# Question: do I need the selector?
# Question: do I need to specify NodePort type?
kind: Service
apiVersion: v1
metadata:
  name: service-catalog-api
  namespace: service-catalog
  labels:
    app: service-catalog-apiserver
spec:
  # type: NodePort
  selector:
    app: service-catalog-apiserver
  ports:
  - name: secure
    protocol: TCP
    port: 443
    targetPort: 8443
    # targetPort: 443
    # nodePort: 30443
