# Service accounts for service catalog api server and controller
# manager. Question: Do I need a namespace for these service accounts?
apiVersion: v1
kind: List
items:
  # The SA for the apiserver
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: "apiserver"
      namespace: service-catalog
  # The SA for the controller-manager
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: "controller-manager"
      namespace: service-catalog
